name: NotrisDefect
main: cabbageroll.notrisdefect.minecraft.Main
version: 1.6.3
api-version: 1.18
softdepend: [ NoteBlockAPI, Netherboard, ProtocolLib ]
commands:
  notrisdefect:
    description: Please use "/nd help" for help
    aliases: [ notris, nd ]
permissions:
  notrisdefect.use.*:
    children:
      notrisdefect.use.singleplayer: true
      notrisdefect.use.multiplayer: true
      notrisdefect.use.skineditor: true
      notrisdefect.use.experimental: true
  notrisdefect.use.singleplayer:
    default: true
  notrisdefect.use.multiplayer:
    default: true
  notrisdefect.use.skineditor:
    default: true
  notrisdefect.use.experimental:
    default: false
  notrisdefect.admin.*:
    children:
      notrisdefect.admin.manage: true
  notrisdefect.admin.manage:
    default: false


