name: NotrisDefect
main: cabbageroll.notrisdefect.Main
version: 1.4.1
api-version: 1.13
softdepend: [ NoteBlockAPI, Netherboard ]
commands:
  notrisdefect:
    description: Please use "/nd help" for help
    aliases: [ notris, nd ]
permissions:
  notrisdefect.use.*:
    children:
      notrisdefect.use.singleplayer: true
      notrisdefect.use.multiplayer: true
      notrisdefect.use.skineditor: true
      notrisdefect.use.experimental: true
  notrisdefect.use.singleplayer:
    default: true
  notrisdefect.use.multiplayer:
    default: true
  notrisdefect.use.skineditor:
    default: false
  notrisdefect.use.experimental:
    default: false
